server:
  port: 8090

logging:
  level:
    org.apache.ibatis.*: debug
    com.example.springbootshardingjdbc.*: debug
    org.springframework.*: debug
    com.mysql.*: debug

mybatis:
  # pom配置src/main/java下的xml为resource
  mapper-locations: classpath:com/example/springbootshardingjdbc/mapper/xml/*Mapper.xml

pagehelper:
  helperDialect: mysql # 设置数据库类型
  reasonable: true #开启合理化：页码<=0 查询第一页，页码>=总页数查询最后一页
  supportMethodsArguments: true #支持通过 Mapper 接口参数来传递分页参数
  params: pageNum=pageIndex;pageSize=pageSize;count=countSql;  # 参数  成员变量 = ${ xx}

spring:
  profiles:
    active: sharding