#spring.main.allow-bean-definition-overriding=true
sharding:
  jdbc:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds0?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: admin
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds1?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: admin
    config:
      sharding:
        props:
          sql.show: true
        tables:
          t_user:  #t_user表
            key-generator-column-name: id  #主键
            actual-data-nodes: ds${0..1}.t_user${0..1}  #数据节点
            database-strategy:  #分库策略
              inline:
                sharding-column: phone
                algorithm-expression: ds${phone % 2}
            table-strategy:  #分表策略
              inline:
                shardingColumn: age
                algorithm-expression: t_user${age % 2}
          t_user_order:
            key-generator-column-name: order_id
            actual-data-nodes: ds${0..1}.t_user_order
            database-strategy:
              inline:
                shardingColumn: user_phone
                algorithm-expression: ds${user_phone % 2}

# 如果不配置重写bean，此处启动时会报DataSource已定义【可查看异常的最后一行，建议配置此参数】，导致失败 查看https://blog.csdn.net/u013810234/article/details/99318113
spring:
  main:
    allow-bean-definition-overriding: true